---

filebeat_version: filebeat-7.15.2-amd64.deb
filebeat_conf: filebeat.yml
kibana_host: 'host: "localhost:5601"'
elastic_hosts: 'hosts: ["localhost:9200"]'

filebeat_inputs:
  - type: log
    enabled: true
    json.keys_under_root: true
    json.overwrite_keys: true
    json.message_key: message
    json.add_error_key: true
    paths:
      - "/home/sysadmin/logger/logger.log"
      - "/var/log/nginx/*.log"

