---

- name: download Elasticsearch
  ansible.builtin.get_url:
    url: "https://artifacts.elastic.co/downloads/elasticsearch/{{ elastic_version }}"
    dest: "/tmp/{{ elastic_version }}"

- name: install Elasticsearch
  ansible.builtin.apt:
    deb: "/tmp/{{ elastic_version }}"
    state: present

- name: copy Elasticsearch configuration
  ansible.builtin.template:
    src: "{{ elastic_conf }}"
    dest: "/etc/elasticsearch/elasticsearch.yml"
    owner: root
    group: root
    mode: 0644

- name: restart Elasticsearch
  ansible.builtin.service:
    name: elasticsearch
    enabled: true
    state: restarted
